spring:
  sql:
    init:
      platform: h2
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:~/animais
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    h2:
      console:
        enabled: true
        path: /h2-console
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name : movie-service







